#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 1
bspc config normal_border_color "#000000"
bspc config active_border_color "#95b6d2"
bspc config focused_border_color "#adcae3"
bspc config presel_feedback_color "#ffffff"

bspc config window_gap 10
bspc config top_padding 24

bspc config split_ratio  0.5
bspc config initial_polarity second_child

bspc config focus_follows_pointer true
bspc config click_to_focus true
